[workspace]
members = ["crates/oppa", "crates/oppa-macros", "crates/oppa-text-dwrite", "crates/spike-textedit", "crates/oppa-shell-win", "crates/oppa-reload", "crates/oppa-cpu", "crates/oppa-vello", "crates/oppa-dom", "crates/oppa-shell-android", "crates/oppa-atspi", "crates/oppa-uia", "crates/oppa-text-android", "crates/oppa-web", "crates/oppa-text-rustybuzz", "crates/oppa-text-linux", "crates/oppa-shell-linux", "crates/oppa-linebreak", "crates/oppa-fps-demo", "crates/oppa-fonts", "crates/oppa-fps", "crates/oppa-controls", "crates/oppa-image", "crates/oppa-testkit", "crates/oppa-app"]
exclude = ["crates/oppa-reload/fixture/hot-fixture", "crates/oppa-android-app", "templates/hello-desktop", "templates/hello-web"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
