//! Hot-reload manifest ABI (M2b §5.1/§5.3, lock #14).
//!
//! The hot crate exports one stable symbol,
//! `oppa_component_manifest() -> ManifestView` (generated by
//! `oppa_macros::component_manifest!`); the core-side harness re-scans it
//! after every swap. Everything here is std-only and dylib-safe by
//! construction:
//!
//! - [`ComponentDesc`] is plain data + function pointers (no vtables, no
//!   `dyn` — nothing that can dangle past unload except through the
//!   drain/adopt protocol below, which never lets it).
//! - Props cross the boundary **typed, never as trait objects**: the
//!   outgoing manifest's [`DrainPropsFn`] clones the concrete props value
//!   (hot code, pre-unload — sound) and hands over a *thin* `*mut c_void`;
//!   the incoming manifest's [`AdoptPropsFn`] checks the type name and
//!   rebuilds the value with fresh clone glue (new code, post-load).
//!   Trait-object vtables from an unloaded dylib can never survive this
//!   protocol — there are none in it.
//! - Same-toolchain rule: both sides are built with the same rustc, so
//!   concrete layouts agree. The type-name check turns a layout mismatch
//!   into a loud eviction, not silent reinterpretation (restart class).

use std::ffi::c_void;

use crate::component::{Ctx, OpaqueProps};
use crate::hash::SymbolHash;
use crate::vnode::VNode;
use crate::worker::HotGeneration;

/// Props payload drained pre-swap: a thin pointer to a concrete
/// `Box<P>` (sized — no vtable) plus nothing else. The owning type name
/// travels core-side as an owned `String` (a `&'static str` would point
/// into the retired image's rodata — reading it post-swap is UB, so
/// the harness copies it before retiring). A null `ptr` is a drain
/// refusal (foreign/stale payload) — the harness evicts loudly.
///
/// Hot-glue panic rule: these functions NEVER panic across the boundary
/// (a Rust panic unwinding through dylib frames aborts the process on
/// Windows). All failures are null returns; all interpretation happens
/// core-side, loudly.
#[repr(C)]
pub struct DrainedProps {
    pub ptr: *mut c_void,
}

/// Outgoing-manifest drain glue (runs pre-unload, hot code — sound):
/// clones the concrete props value behind `props` and returns it boxed
/// as a thin pointer. Never fails: the props came from this manifest's
/// own component.
pub type DrainPropsFn = unsafe extern "C" fn(*const OpaqueProps) -> DrainedProps;

/// Incoming-manifest adopt glue (runs post-load, new code): `expected` is
/// a core-owned `CString` of the drained type name, kept alive for the
/// call. On match, rebuilds the value with fresh clone glue tagged
/// `into` and returns ownership (core takes it with `Box::from_raw`).
/// On mismatch returns null — the payload then leaks by design (its type
/// is unknown post-unload, so it cannot be freed) and the harness counts
/// an eviction. Eviction is restart-class and rare; the leak is bounded
/// (one props value) and reported, never silent.
pub type AdoptPropsFn = unsafe extern "C" fn(
    DrainedProps,
    into: HotGeneration,
    expected: *const std::ffi::c_char,
) -> *mut OpaqueProps;

/// One hot-swappable component: stable identity + typed boundary glue.
/// Plain data + function pointers: `Clone + Copy + Send + Sync`, so the
/// manifest table can live in a `static` and cross the dylib boundary.
/// The harness holds the provider alive while any copy is used.
///
/// Mount-time fallbacks (which close over typed render fns) live one
/// layer up as `component::RenderFn` (`Rc`); they are built at use time,
/// never stored here.
#[derive(Clone, Copy)]
pub struct ComponentDesc {
    /// Stable identity across swaps (hot-reload key, §5.1).
    pub symbol: SymbolHash,
    /// `std::any::type_name::<P>()` of the props — the adopt check.
    pub props_type: &'static str,
    /// Render entry point (Rust ABI, same-toolchain rule).
    pub render: fn(&Ctx, &OpaqueProps) -> VNode,
    pub drain_props: DrainPropsFn,
    pub adopt_props: AdoptPropsFn,
}

/// The stable export shape: `#[no_mangle] pub extern "C" fn
/// oppa_component_manifest() -> ManifestView`.
#[repr(C)]
pub struct ManifestView {
    pub entries: *const ComponentDesc,
    pub len: usize,
}

// SAFETY: the pointed-to table lives as long as its provider — `'static`
// for compiled-in manifests, and the harness holds the `Library` alive
// for dylib manifests. View itself carries no lifetime by FFI necessity;
// `as_slice` is `unsafe` with the provider-alive contract.
unsafe impl Send for ManifestView {}
unsafe impl Sync for ManifestView {}

impl ManifestView {
    /// Views the exported table.
    ///
    /// # Safety
    ///
    /// The providing image must still be loaded (the harness holds the
    /// `Library` alive for dylib manifests; compiled-in manifests are
    /// `'static`). The table itself is never mutated after first build.
    pub unsafe fn as_slice(&self) -> &[ComponentDesc] {
        if self.entries.is_null() || self.len == 0 {
            return &[];
        }
        std::slice::from_raw_parts(self.entries, self.len)
    }
}
